spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: flight-tracker-group
    topic:
      flight-positions: flight-positions
      ping-created: ping-created
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  
  datasource:
    url: jdbc:h2:mem:flighttracker
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  
  h2:
    console:
      enabled: true
      path: /h2-console 

  default:
    request:
      limit: 50
