spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: flight-tracker-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "dev.luismachadoreis.flighttracker.server.ping.application.dto"
    topic:
      flight-positions: flight-positions
      ping-created: ping-created

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true

  datasource:
    writer:
      jdbcUrl: jdbc:postgresql://localhost:5432/flighttracker
      username: flighttracker
      password: flighttracker
      driverClassName: org.postgresql.Driver
      type: com.zaxxer.hikari.HikariDataSource
    reader:
      jdbcUrl: jdbc:postgresql://localhost:5433/flighttracker
      username: flighttracker
      password: flighttracker
      driverClassName: org.postgresql.Driver
      type: com.zaxxer.hikari.HikariDataSource

  redis:
    host: localhost
    port: 6379

logging:
  level:
    root: INFO
    dev.luismachadoreis.flighttracker.server: DEBUG
    org.springframework.kafka: INFO
    org.hibernate: INFO
    org.springframework.data: INFO

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    filter: true
    syntax-highlight:
      activated: true
      theme: monokai
  show-actuator: true
  packages-to-scan: dev.luismachadoreis.flighttracker.server.ping.api

api:
  title: Flight Tracker Event Server API
  description: |
    API for tracking and managing flight position data.
    
    This service provides endpoints to:
    - Retrieve recent flight position pings
    - Track aircraft movements
    - Monitor flight data in real-time
  version: 0.0.1-SNAPSHOT
  contact:
    name: Luis Machado Reis
    email: luis.machadoreis@dev.com
    url: https://github.com/luismachadoreis
  license:
    name: MIT License
    url: https://opensource.org/licenses/MIT
  servers:
    - url: http://localhost:8080
      description: Local Development Server
    - url: https://dev-api.flighttracker.com
      description: Development Server
    - url: https://staging-api.flighttracker.com
      description: Staging Server
    - url: https://api.flighttracker.com
      description: Production Server

app:
  read-write-routing:
    enabled: false